### ISSUE TITLE
SimTests: Event Indexing failed

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#184]
Occurs very irregularly.

```
build-an-atom : phet-io-tests
2 out of 3 tests passed. 1 failed.
SimTests: Event Indexing failed:
Message index 3 should align
    at doesEventHaveValidIndex (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:285:20)
    at phetioEventsListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:303:11)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:140:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:198:13)

SimTests: Event Indexing failed:
Message index 4 should align
    at doesEventHaveValidIndex (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:285:20)
    at phetioEventsListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:303:11)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:140:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:198:13)

SimTests: Event Indexing failed:
Message index 5 should align
    at doesEventHaveValidIndex (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:285:20)
    at phetioEventsListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:303:11)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:140:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:198:13)

SimTests: Event Indexing failed:
Message index 6 should align
    at doesEventHaveValidIndex (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:285:20)
    at phetioEventsListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/js/tests/SimTests.js?bust=1519680706236:303:11)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:140:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1519678684649/phet-io-wrappers/common/js/SimIFrameClient.js:198:13)
```

**Comment by samreid** [comment]
In local tests, I'm seeing `Uncaught TypeError: Converting circular structure to JSON` about half the time.

**Comment by samreid** [comment]
I haven't seen any more trouble since the preceding commits.  @phet-steele can you keep an eye on Bayes CT and let me know how it goes?  Close if all is clear for a few days.

**Comment by phet-steele** [comment]
Not appearing anymore.
