### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#197]
```
build-an-atom : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543915190158:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
build-an-atom : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928586205:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
build-an-atom : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.atomScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showElementNameCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showNeutralOrIonCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: build-an-atom: iframe api failed:
phetioDocumentation expected for buildAnAtom.symbolScreen.view.labelVisibilityControlPanel.showStableOrUnstableCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543909265906:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
```

**Comment by jbphet** [comment]
I haven't done anything recently on this sim, and `phetioDocumentation` seems to be at the core of the issue.  Assigning to @zepumph.

**Comment by jbphet** [comment]
I'm raising the priority on this issue since it's been happening for over a month, and I'm the responsible dev for this sim, and it's bothering me that it is frequently failing CT.

**Comment by jbphet** [comment]
@zepumph - please let me know if there is something I can and should do to help resolve this issue, or if we need to get someone else on it.

**Comment by zepumph** [comment]
I will not get to it until Wednesday, but I'll look at it then with @samreid.

**Comment by zepumph** [comment]
Note that the current CT error is different from the above one:
```
build-an-atom : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: build-an-atom: iframe api failed:
Changed state should now have one item in it.
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1547485030218/phet-io-wrappers/js/tests/SimTests.js?bust=1547486545175:187:30)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1547485030218/phet-io-wrappers/common/js/Client.js:311:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1547485030218/phet-io-wrappers/common/js/Client.js:348:15)


id: Bayes Chrome
Approximately 1/14/2019, 7:57:10 AM
```

**Comment by zepumph** [comment]
The above commits plus the work done in phetsims/phet-io-wrappers#233 should have completely cleaned up build an atom. Let's create new issues if there are new errors.
