### ISSUE TITLE
CT phetioID

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#205]
```
build-an-atom : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: buildAnAtom.atomScreen.model.particleAtom.protons.lengthProperty
Error: Assertion failed: phetioID already registered: buildAnAtom.atomScreen.model.particleAtom.protons.lengthProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/phet-io/js/phetioEngine.js?:365:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/phet-io/js/phetioEngine.js?:482:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/Tandem.js?:146:40)
    at NumberProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/PhetioObject.js?:300:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/Property.js?:69:7)
    at new NumberProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/NumberProperty.js?:56:7)
    at new ObservableArray (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/ObservableArray.js?:52:27)
    at ObservableArray.map (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/ObservableArray.js?:310:31)
id: Bayes Chrome
Approximately 9/13/2019, 2:48:20 PM
build-an-atom : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: buildAnAtom.atomScreen.model.particleAtom.protons.lengthProperty
Error: Assertion failed: phetioID already registered: buildAnAtom.atomScreen.model.particleAtom.protons.lengthProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/phet-io/js/phetioEngine.js?:365:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/phet-io/js/phetioEngine.js?:482:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/Tandem.js?:146:40)
    at NumberProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/PhetioObject.js?:300:19)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/tandem/js/PhetioObject.js?:131:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/Property.js?:69:7)
    at new NumberProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/NumberProperty.js?:56:7)
    at new ObservableArray (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/ObservableArray.js?:52:27)
    at ObservableArray.map (https://bayes.colorado.edu/continuous-testing/snapshot-1568407700856/axon/js/ObservableArray.js?:310:31)
id: Bayes Chrome
Approximately 9/13/2019, 2:48:20 PM
```

**Comment by jbphet** [comment]
On Slack, @samreid said that he had a potential fix.  Assigning to him.

**Comment by samreid** [comment]
Thanks @jbphet, it looks like the potential fix is working nicely.  Closing.
