### ISSUE TITLE
CT: parent should not have child: particle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/build-an-atom#215]
CCK has a similar error (see https://github.com/phetsims/circuit-construction-kit-common/issues/580), maybe they have something in common.

```
build-an-atom : fuzz : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22fuzz%22%2C%22require.js%22%5D%2C%22snapshotName%22%3A%22snapshot-1588863160488%22%2C%22timestamp%22%3A1588866019019%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: parent should not have child: particle
Error: Assertion failed: parent should not have child: particle
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/assert/js/assert.js:22:13)
at new Tandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/tandem/js/Tandem.js:88:17)
at new GroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/tandem/js/Tandem.js:541:5)
at Tandem.createGroupTandem (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/tandem/js/Tandem.js:305:12)
at new NonInteractiveSchematicAtomNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/build-an-atom/js/game/view/NonInteractiveSchematicAtomNode.js:43:38)
at new SchematicToSymbolChallengeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/build-an-atom/js/game/view/SchematicToSymbolChallengeView.js:51:29)
at SchematicToSymbolChallenge.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/build-an-atom/js/game/model/SchematicToSymbolChallenge.js:41:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/build-an-atom/js/game/view/BAAGameScreenView.js:143:35
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588863160488/axon/js/Property.js:270:25)
id: Bayes Chrome
Snapshot from 5/7/2020, 8:52:40 AM
```

**Comment by jbphet** [comment]
This was discussed during dev meeting yesterday, and is related to the now-deprecated `GroupTandem` class.  Someone - I think it was @samreid - agreed to take it on.  Assigning to him for now.

The problem hasn't appeared for the last two rounds of CT, but I don't see any recent commits that appear related, so AFAIK it still needs to be fixed.

**Comment by samreid** [comment]
I think @zepumph said he addressed this, is that correct?

**Comment by zepumph** [comment]
Yes sorry I didn't ping this issue, it was fixed from https://github.com/phetsims/tandem/commit/48cf7e3aa38f1bf6384f8cb056cf5cb026260e33. I don't see it on CT this morning. Closing
