### ISSUE TITLE
CT: lint is failing

### ISSUE THREAD

**Issue by jbphet** [phetsims/build-an-atom#225]
This sim is failing lint, and this was detected by continuous testing.  Here's a screenshot of the problem:

![image](https://user-images.githubusercontent.com/3082831/125116907-a7d8d680-e0aa-11eb-9282-9a3280b053db.png)

This is the commit where it was introduced:

4b7bd3d21a96fa940f9e70e74bac9df70f5ba1b3

Assigning to @Luisav1, since that's who made the commit.  @Luisav1 - Please set up git commit hooks, since it will help to prevent commits that cause lint to break.

**Comment by KatieWoe** [comment]
There is another issue that seems to be connected.
```
build-an-atom : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625863978445%22%2C%22timestamp%22%3A1625866045788%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught ReferenceError: options is not defined
ReferenceError: options is not defined
at BuildAnAtomModel.setAtomConfiguration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/common/model/BuildAnAtomModel.js:372:5)
at SymbolToSchematicChallengeView.displayCorrectAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/game/view/SymbolToSchematicChallengeView.js:78:37)
at Object.ChallengeView.stateChangeHandlers.<computed> [as displayingCorrectAnswer] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/game/view/ChallengeView.js:174:12)
at handleStateChange (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/game/view/ChallengeView.js:182:46)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/axon/js/TinyEmitter.js:86:9)
at StringProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/axon/js/Property.js:271:23)
at StringProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/axon/js/Property.js:186:14)
at SymbolToSchematicChallenge.displayCorrectAnswer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/game/model/BAAGameChallenge.js:158:33)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/game/view/ChallengeView.js:112:35)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625863978445/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 7/9/2021, 2:52:58 PM

----------------------------------

build-an-atom : lint
Lint failed with status code 6:
Running "lint" task

/data/share/phet/continuous-testing/ct-snapshots/1625863978445/build-an-atom/js/common/model/BuildAnAtomModel.js
372:10 error 'options' is not defined no-undef

✖ 1 problem (1 error, 0 warnings)

Warning: 1 errors and 0 warnings Use --force to continue.

Aborted due to warnings.
Snapshot from 7/9/2021, 2:52:58 PM
```

**Comment by KatieWoe** [comment]
Also may impact perennial:
```
perennial : lint-everything
Lint-everything failed with status code 6:
Running "lint-everything" task

/data/share/phet/continuous-testing/ct-snapshots/1625861490251/build-an-atom/js/common/model/BuildAnAtomModel.js
372:10 error 'options' is not defined no-undef

✖ 1 problem (1 error, 0 warnings)

Warning: 1 errors and 0 warnings Use --force to continue.

Aborted due to warnings.
Snapshot from 7/9/2021, 2:11:30 PM
```

**Comment by pixelzoom** [comment]
@Luisav1 To set up git hooks, see step 13 of https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#utilities-and-instrumentation-for-development-and-testing.  Also highly recommended to read this entire document, if you haven't already. 

If you have trouble setting up GitHooks, contact one of the PhET developers on the Slack developer or dev-public channels.  And in the meantime, run `grunt lint` from the command line before pushing committing or pushing changes.

Lastly... After you have pushed changes, you should get in the habit of looking at PhET's CT (Continuous Test) webpage, at https://bayes.colorado.edu/continuous-testing/aqua/html/continuous-report.html.   Simulations are continuously tested on a PhET server , and the results are shown here.  Red indicates a problem, click on cells to get details.

**Comment by Luisav1** [comment]
@pixelzoom Thank you, I have set it up now and also ran grunt lint before committing. I hope it is fixed now but I can see that it's still red on PhET's CT webpage. I'm hoping that it's just taking time to update?

**Comment by pixelzoom** [comment]
Yes, CT can take awhile to update. It doesn't test your changes immediately, they will be tested on the next test cycle.  The timestamp at the top of each column indicates when the tests were run.

**Comment by Luisav1** [comment]
I see, that makes sense. CT has updated by now and no longer shows any issues in build-an-atom so I am closing this. I've also got git hooks set up well too.
