### ISSUE TITLE
CT Class constructor LinearFunction cannot be invoked without new

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#228]
```
build-an-atom : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637639203227%22%2C%22timestamp%22%3A1637641043460%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Class constructor LinearFunction cannot be invoked without 'new'
TypeError: Class constructor LinearFunction cannot be invoked without 'new'
at ParticleAtom.reconfigureNucleus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/shred/js/model/ParticleAtom.js:469:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/shred/js/view/ElectronShellView.js:131:18
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Multilink.js:37:21)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/TinyEmitter.js:65:17)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:193:27)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:137:22)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/DerivedProperty.js:83:19)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/TinyEmitter.js:65:17)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:193:27)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:137:22)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:46:43 PM

----------------------------------

build-an-atom : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1637639203227%22%2C%22timestamp%22%3A1637640902777%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Class constructor LinearFunction cannot be invoked without 'new'
TypeError: Class constructor LinearFunction cannot be invoked without 'new'
at ParticleAtom.reconfigureNucleus (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/shred/js/model/ParticleAtom.js:469:35)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/shred/js/view/ElectronShellView.js:131:18
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Multilink.js:37:21)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/TinyEmitter.js:65:17)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:193:27)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:137:22)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/DerivedProperty.js:83:19)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/TinyEmitter.js:65:17)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:193:27)
at NumberProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637639203227/chipper/dist/axon/js/Property.js:137:22)
id: Bayes Chrome
Snapshot from 11/22/2021, 8:46:43 PM
```

**Comment by jbphet** [comment]
This sim is passing CT at this time, and has been for a while, here's a screenshot:

![image](https://user-images.githubusercontent.com/3082831/143931258-2501a148-c091-45dd-a4ee-109455ffdc37.png)

I'm fairly sure that this problem was related to the changes being made to support TypeScript, and not a problem with the sim itself.  Since it appears to have gone away, I'm going to assume that the common-code core problem has been corrected and close this issue.
