### ISSUE TITLE
CT dpendencies should be defined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-an-atom#234]
```
build-an-atom : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/build-an-atom/build-an-atom_en.html?continuousTest=%7B%22test%22%3A%5B%22build-an-atom%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652693017321%22%2C%22timestamp%22%3A1652697903497%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652693017321/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 3:23:37 AM
```

**Comment by jbphet** [comment]
This seems to have disappeared, see the screenshot below. Since I haven't been doing any work on this sim, I'm going to assume the problem was something transient in common code and close.

![image](https://user-images.githubusercontent.com/3082831/168859690-1e7220c5-e59f-4128-97a7-ac61b21cc991.png)
